apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
//apply plugin: 'com.github.dcendents.android-maven'
group = 'com.github.udesk'

repositories {
    maven { url 'https://oss.jfrog.org/libs-snapshot' }
    maven { url 'https://jitpack.io' }
    mavenCentral()
    google()
}

android {
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
        namespace 'cn.udesk'
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
}
// 添加发布配置
afterEvaluate {
    publishing {
        publications {
            // 创建一个名为 'release' 的发布任务
            release(MavenPublication) {
                // 从 release 组件创建发布内容
                from components.release

                // 这里的 groupId 建议遵循 JitPack 的多模块规范
                // 格式：com.github.用户名.仓库名
                groupId = 'com.github.LiuShuai92.UdeskSDK-Android'

                // 这里的 artifactId 就是模块名
                artifactId = 'UdeskSDKUI'

                // 版本号通常跟随项目 git tag，这里可以动态获取或写死
                version = 'v5.6.9'
            }
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation 'com.github.chrisbanes:PhotoView:2.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation group: 'org.ccil.cowan.tagsoup', name: 'tagsoup', version: '1.2.1'
    implementation files('libs/udesk-asmack-8-4.0.6.jar')
    api files('libs/udesk_sdk_5.4.3.jar')
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
